### ISSUE TITLE
What exactly does the mod do

### ISSUE THREAD

**Issue by ghost** [Kirilliriks/BoosterCore#1]
What exactly does the mod do
It changes texture or generation
if the latter then how does it affect the existing worlds

**Comment by Kirilliriks** [comment]
> What exactly does the mod do
> It changes texture or generation
> if the latter then how does it affect the existing worlds

The modification removes the lowest polygons of the lowest bedrock layer, in vanilla minecraft the modification will not affect the gameplay, in the case of other mods (which change the rendering in one way or another) conflicts are possible, but I doubt that, this is unlikely. The modification does NOT change the generation!

**Comment by Kirilliriks** [comment]
Are you sure you are asking a question about BoosterCore? This is a server core for minecraft beta 1.4_01 inspired by Bukkit.

If you're talking about Bedrodium: The modification removes the lowest polygons of the lowest bedrock layer, in vanilla minecraft the modification will not affect the gameplay, in the case of other mods (which change the rendering in one way or another) conflicts are possible, but I doubt that, this is unlikely. The modification does NOT change the generation!

**Comment by ghost** [comment]
> Are you sure you are asking a question about BoosterCore? This is a server core for minecraft beta 1.4_01 inspired by Bukkit.
> 
> If you're talking about Bedrodium: The modification removes the lowest polygons of the lowest bedrock layer, in vanilla minecraft the modification will not affect the gameplay, in the case of other mods (which change the rendering in one way or another) conflicts are possible, but I doubt that, this is unlikely. The modification does NOT change the generation!

I asked about the Bedrodium mod
i clicked on the git hub tab on the mod page

**Comment by Kirilliriks** [comment]
Oh, my mistake, I accidentally left a link to my other project, here is the correct link if required, I apologize, I hope I answered your question here. https://github.com/Kirilliriks/Bedrodium/issues
