### ISSUE TITLE
Makes all polygons at that level invisible

### ISSUE THREAD

**Issue by griffin4cats** [Kirilliriks/BoosterCore#2]
I have a datapack which extends the world in the end downwards, and planes at that level will be invisible.
This should at least be disabled in the end, I think.

**Comment by Kirilliriks** [comment]
Sorry on https://modrinth.com/ I left a wrong Issue link, sorry. I have already been informed about this problem, I will try to solve it, if you are interested in this topic, then here is the link - https://github.com/Kirilliriks/Bedrodium/issues/3.
